"""Well-known folder names used throughout the darkroom workflow."""

PUBLISH_FOLDER = "PUBLISH"
PHOTOS_FOLDER = "PHOTOS"
VIDEOS_FOLDER = "VIDEOS"

FOLDERS_EXEMPT_FROM_TIDY = {PUBLISH_FOLDER, PHOTOS_FOLDER, VIDEOS_FOLDER}
